enableGlobalCache: true

globalFolder: ../.yarn/berry

pnpEnableEsmLoader: true

packageExtensions:
  '@nestjs/microservices@*':
    dependencies:
      '@grpc/proto-loader': '*'
      ioredis: '*'
      kafkajs: '*'
  '@typescript-eslint/utils@*':
    dependencies:
      eslint: '*'
  'knex@*':
    dependencies:
      pg-query-stream: '*'
      pg: '*'

yarnPath: .yarn/releases/yarn-remote.mjs
