enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  '@deepkit/broker@*':
    peerDependencies:
      '@deepkit/logger': '*'
  '@deepkit/framework-debug-api@*':
    peerDependencies:
      rxjs: '*'
  '@deepkit/framework@*':
    peerDependencies:
      '@deepkit/filesystem': '*'
      rxjs: '*'
  '@deepkit/sql@*':
    dependencies:
      ts-node: '*'
      typescript: '*'
  '@deepkit/template@*':
    dependencies:
      pirates: '*'
  '@monstrs/tools-runtime@*':
    dependencies:
      '@deepkit/type-compiler': 1.0.1-alpha.155

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-file.mjs
