enableGlobalCache: true

globalFolder: ../.yarn/berry

pnpEnableEsmLoader: true

packageExtensions:
  '@typescript-eslint/utils@*':
    dependencies:
      eslint: '*'

yarnPath: .yarn/releases/yarn-remote.mjs
