version: '3.8'

volumes:
  yarn:

services:
  yarn:
    image: node:22
    working_dir: /workspace
    volumes:
      - yarn:/.yarn/berry
      - ./:/workspace
    entrypoint: yarn

  database:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=database
    ports:
      - 5432:5432

  minio:
    image: minio/minio
    command: server /data --console-address :9001
    environment:
      - MINIO_ROOT_USER=accesskey
      - MINIO_ROOT_PASSWORD=secretkey
      - MINIO_DOMAIN=localhost
    volumes:
      - .data:/data
    ports:
      - 9001:9001
      - 9000:9000
